const names: string[] = [];
names.push("a");
names.push("b");
names.push("c");
names.push("d");
names.push("e");
names.push("f");
names.push("g");
names.push("h");
names.push("i");
names.push("j");
names.push("k");
names.push("l");
names.push("m");
names.push("n");
// console.log(names);
// console.log(names.indexOf("a"));
// console.log(names.indexOf("b"));
// console.log(names.indexOf("c"));
// console.log(names.indexOf("d"));
// console.log(names.indexOf("e"));
// console.log(names.indexOf("f"));
// console.log(names.indexOf("g"));
// console.log(names.indexOf("h"));
// console.log(names.indexOf("i"));
// console.log(names.indexOf("k"));
// console.log(names.indexOf("l"));
// console.log(names.indexOf("m"));
// console.log(names.indexOf("n"));
names.length;
console.log(names.length);
