// class Car {
//   //field
//   engine: string;

//   //constructor
//   constructor(engine: string) {
//     this.engine = engine;
//   }

//   //function
//   disp(): void {
//     console.log("Engine is  :   " + this.engine);
//   }
// }

//Generated by typescript 1.8.10
var Car = (function () {
  //constructor
  function Car(engine) {
    this.engine = engine;
  }

  //function
  Car.prototype.disp = function () {
    console.log("Function displays Engine is  :   " + this.engine);
  };
  return Car;
})();

//create an object
var obj = new Car("XXSY1");

//access the field
console.log("Reading attribute value Engine as :  " + obj.engine);

//access the function
obj.disp();
